### ISSUE TITLE
Super laggy

### ISSUE THREAD

**Issue by CuteWaterBeary** [karstenpedersen/obsidian-vimium#9]
This is a great idea but I am experiencing huge lag. Even when I reduced the css selectors to just  `.is-clickable` it still takes a full 3 seconds to show (which is just the left side file tree which contains about 100 items in the root directory). If I use the default enabled list, it takes 5-10 seconds.

It appears that it is searching for elements that are hidden - not in scroll view or hidden under a popup menu - because the key popups appears going down beyond what I can see on the tree view and showing up in areas where there is nothing unless I click a menu to show up. Perhaps this is one area where it slows down? Maybe theres a way to cache things too?

**Comment by jfsicilia** [comment]
I made a PR (https://github.com/karstenpedersen/obsidian-vimium/pull/11) solving lag issues (minimum 20x performance increase). I can use it now without issues.

**Comment by CuteWaterBeary** [comment]
Just tried it out - it works great. Hopefully it gets merged soon

**Comment by Fred-Vatin** [comment]
I don’t know why this PR is still not merged. It is awesome.
